### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Maryada-27** [inivation/caer#160]
Anyone aware of error...

In file included from /usr/include/libcaer/libcaer.h:18:0,
                 from /usr/include/libcaer/events/common.h:14,
                 from /usr/include/libcaer/events/frame.h:19,
                 from /media/maddy/development/caer-master/modules/cameracalibration/calibration_wrapper.h:10,
                 from /media/maddy/development/caer-master/modules/cameracalibration/calibration_wrapper.cpp:1:
/usr/include/c++/5/cstdlib: In function ‘long long int std::abs(long long int)’:
/usr/include/c++/5/cstdlib:174:20: error: conflicting declaration of C function ‘long long int std::abs(long long int)’
   abs(long long __x) { return __builtin_llabs (__x); }
                    ^
/usr/include/c++/5/cstdlib:166:3: note: previous declaration ‘long int std::abs(long int)’
   abs(long __i) { return __builtin_labs(__i); }
   ^
modules/cameracalibration/CMakeFiles/cameracalibration.dir/build.make:110: recipe for target 'modules/cameracalibration/CMakeFiles/cameracalibration.dir/calibration_wrapper.cpp.o' failed
make[2]: *** [modules/cameracalibration/CMakeFiles/cameracalibration.dir/calibration_wrapper.cpp.o] Error 1
CMakeFiles/Makefile2:236: recipe for target 'modules/cameracalibration/CMakeFiles/cameracalibration.dir/all' failed
make[1]: *** [modules/cameracalibration/CMakeFiles/cameracalibration.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by llongi** [comment]
Commit 86038a3edcab1fd66c7962f2c4cd0d5247a2fae3 should fix this, please test. It seems older compilers can get confused about C++ function overloading in some corner cases.
